// Generated by Selenium IDE
package search_page.functionalityTest;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VirtualKeyboardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public static void waitForWindow(int timeout) {
      try {
          Thread.sleep(timeout);
      } catch (InterruptedException e) {
          e.printStackTrace();
      }
  }
  @Test
  public void virtualKeyboard() {
    // General Description: this code is checking the searching tool Google with virtual keyboard.
    // WEB URL : "https://www.google.com/"

    //Action: Click on the url: "https://www.google.com/"
    //Action: Click on the URL: "https://www.google.com/".
    //Action: Visit the URL: "https://www.google.com/".
    //Action: Open the URL: "https://www.google.com/".
    //Action: Navigate to the URL: "https://www.google.com/".
    //Action: Access the URL: "https://www.google.com/".
    driver.get("https://www.google.com/");
    driver.manage().window().maximize();
    waitForWindow(3000);

    //Action: Click on the keyboard button at the end of the search field.
    //Action: Press the keyboard button located at the end of the search field.
    //Action: Select the keyboard button positioned at the end of the search field.
    //Action: Click on the keyboard icon situated at the end of the search field.
    //Action: Activate the keyboard button found at the end of the search field.
    driver.findElement(By.cssSelector(".ly0Ckb")).click();
    waitForWindow(3000);

    //Action: Type "TikTok" into the searching field by virtual keyboard.
    //Action: Input "tiktok" into the search field using the virtual keyboard.
    //Action: Enter "tiktok" into the search field via the virtual keyboard.
    //Action: Type "tiktok" on the virtual keyboard and input it into the search field.
    //Action: Use the virtual keyboard to type "TikTok" into the search field.
    //Action: Input "tiktok" into the search field by using the virtual keyboard.
    {
      WebElement element = driver.findElement(By.cssSelector(".vk-t"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("kbd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("kbd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".vk-t")).click();
    driver.findElement(By.id("K84")).click();
    driver.findElement(By.id("K73")).click();
    driver.findElement(By.cssSelector(".vk-sf-h:nth-child(1)")).click();
    driver.findElement(By.id("K84")).click();
    driver.findElement(By.cssSelector(".vk-sf-h:nth-child(1)")).click();
    driver.findElement(By.id("K75")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".vk-t"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#kbd > div:nth-child(2) > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#kbd > div:nth-child(2) > div:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".vk-t")).click();
    driver.findElement(By.id("APjFqb")).click();
    waitForWindow(3000);

    //Action: Click on the first suggested keyword.
    //Action: Click on the "TikTok" on the suggested list under the searching field.
    //Action: Select "tiktok" from the list of suggestions below the search field and click on it.
    //Action: Choose "tiktok" from the suggested options under the search field and proceed with a click.
    driver.findElement(By.xpath("//div[@id=\'jZ2SBf\']/div/span")).click();
      waitForWindow(3000);

    //Action: Click on the first result appeared.
    //Action: Click on the first result appeared in the new page.
    //Action: Select the initial result that shows up on the fresh page.
    //Action: Choose the first outcome displayed on the newly opened page.
    //Action: Click on the initial search result visible on the recently loaded page.
    //Action: Opt for the first link that appears on the newly opened page.
    //Action: Click on the primary result presented on the fresh page.
    driver.findElement(By.cssSelector(".tF2Cxc > .yuRUbf .LC20lb")).click();
    driver.close();
  }
}
