package forum;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import io.github.cdimascio.dotenv.Dotenv;

import java.util.*;

public class LoginCorrectTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    String email;
    String password;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        Dotenv dotenv = Dotenv.load();
        email = dotenv.get("PIAZZA_EMAIL");
        password = dotenv.get("PIAZZA_PASSWORD");
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void piazza() throws InterruptedException {
        driver.get("https://piazza.com/");
//        driver.manage().window().setSize(new Dimension(784, 816));
        Thread.sleep(3000);
        driver.findElement(By.id("login_button")).click();
        Thread.sleep(3000);
        driver.findElement(By.id("email_field")).click();
        driver.findElement(By.id("email_field")).sendKeys(email);
        driver.findElement(By.id("password_field")).click();
        driver.findElement(By.id("password_field")).sendKeys(password);
        driver.findElement(By.id("modal_login_button")).click();
        driver.close();
    }
}

