package news_page;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logout() throws InterruptedException {
    // Action: Open website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(804, 816));
    // Action: Click on Login button
    driver.findElement(By.cssSelector(".account-login")).click();
    Thread.sleep(3000);
    // Action: Click on Email text field
    driver.findElement(By.id("txtLoginEmail")).click();
    // Action: Enter email
    driver.findElement(By.id("txtLoginEmail")).sendKeys("thht200603@gmail.com");
    // Action: Click on Password text field
    driver.findElement(By.id("txtLoginPassword")).click();
    // Action: Enter password
    driver.findElement(By.id("txtLoginPassword")).sendKeys("123456789");
    // Action: Press ENTER
    driver.findElement(By.id("txtLoginPassword")).sendKeys(Keys.ENTER);
    Thread.sleep(3000);
    {
      WebElement element = driver.findElement(By.cssSelector(".account-name"));
      Actions builder = new Actions(driver);
      // Action: Hover the account name button
      builder.moveToElement(element).perform();
    }
    // Action: Click on Logout button
    driver.findElement(By.cssSelector(".info-user > li:nth-child(4) > a")).click();
    driver.close();
  }
}
