package e_commerce_page;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginCorrect() throws InterruptedException {
    driver.get("https://shopee.vn/buyer/login?next=https%3A%2F%2Fshopee.vn%2Fbuyer%2Flogin%3Fnext%3Dhttps%253A%252F%252Fshopee.vn%252F");
    driver.findElement(By.name("loginKey")).click();
    driver.findElement(By.name("loginKey")).sendKeys("tuannghia236");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Iloveyou3000", Keys.ENTER);
    Thread.sleep(5000);
    String currentURL = driver.getCurrentUrl();
    if (currentURL.equals("https://shopee.vn/verify/ivs?is_initial=true")) {
      driver.findElement(By.cssSelector(".dWxniD")).click();
      Thread.sleep(30000);
      String newTitle = driver.getTitle();
      Assert.assertEquals("Shopee Việt Nam | Mua và Bán Trên Ứng Dụng Di Động Hoặc Website", newTitle);
      System.out.println("Done");
    } else {
      String newTitle = driver.getTitle();
      Assert.assertEquals("Shopee Việt Nam | Mua và Bán Trên Ứng Dụng Di Động Hoặc Website", newTitle);
      System.out.println("Done");
      Thread.sleep(5000);
    }
//    {
//      WebElement element = driver.findElement();
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    Thread.sleep(5000);
//    String newTitle = driver.getTitle();
//    Assert.assertEquals("Shopee Việt Nam | Mua và Bán Trên Ứng Dụng Di Động Hoặc Website", newTitle);
//    System.out.println("Done");
//    Thread.sleep(5000);
    driver.close();
  }
}
