package e_commerce_page;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searching() throws InterruptedException {
    driver.get("https://shopee.vn/");
//    WebDriverWait wait = new WebDriverWait(driver, 10);
    Thread.sleep(5000);
    driver.navigate().back();
    Thread.sleep(5000);
//    driver.findElement(By.cssSelector(".shopee-searchbar-input__input")).click();
//    driver.findElement(By.cssSelector(".shopee-searchbar-input__input")).sendKeys("giày");
//    driver.findElement(By.cssSelector(".shopee-searchbar-input__input")).sendKeys(Keys.ENTER);
//    driver.findElement(By.cssSelector(".col-xs-2-4:nth-child(1) .line-clamp-2")).click();
//    js.executeScript("window.scrollTo(0,0)");
//    driver.findElement(By.cssSelector(".WBVL_7 > span")).click();
  }
}
