package Article.anotherNewsFunctionality;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IntegrationFunctionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void integrationFunction() {

    //General Description: this test is going to check if the weather and another functionality integrated into newspaper.
    // Web url: https://nhandan.vn/

    // Action: Open the url "https://nhandan.vn/"
    // Action: Access the webpage "https://nhandan.vn/"
    // Action: Navigate to the URL "https://nhandan.vn/"
    // Action: Visit the link "https://nhandan.vn/"
    // Action: Go to the address "https://nhandan.vn/"
    // Action: Browse to the website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    //Action: Click on the "Tin địa phương" button.
    //Action: Clicking on the "Tin địa phương" button.
    //Action: Selecting the "Tin địa phương" button with a click.
    //Action: Accessing the "Tin địa phương" option by clicking.
    //Action: Engaging the "Tin địa phương" button with a click.
    //Action: Choosing the "Tin địa phương" option by clicking on it.
    driver.findElement(By.cssSelector(".region-3 li:nth-child(2) > a")).click();

    // Action: Find weather section and click on "Nam Định".
    //Action: Finding the weather section and clicking on "Nam Định".
    //Action: Locating the weather section and selecting "Nam Định" with a click.
    //Action: Accessing the weather section and engaging with "Nam Định" by clicking.
    //Action: Navigating to the weather section and clicking on "Nam Định".
    //Action: Identifying the weather section and choosing "Nam Định" by clicking on it.
    driver.findElement(By.id("weather-location")).click();
    {
      WebElement dropdown = driver.findElement(By.id("weather-location"));
      dropdown.findElement(By.xpath("//option[. = 'Nam Định']")).click();
    }

    // Action: Click on the "Tỷ giá" button.
    //Action: Clicking on the "Tỷ giá" button.
    //Action: Selecting the "Tỷ giá" button with a click.
    //Action: Accessing the "Tỷ giá" option by clicking.
    //Action: Engaging the "Tỷ giá" button with a click.
    //Action: Choosing the "Tỷ giá" option by clicking on it.
    driver.findElement(By.linkText("Tỷ giá")).click();
    driver.close();
  }
}
