// Generated by Selenium IDE
package Article.anotherNewsFunctionality;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MostRead2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mostRead2() {
    // GENERAL DESCRIPTION: This test is check the most read article while reading another article.
    // WEB URL: https://nhandan.vn/

    // Action: Open the url "https://nhandan.vn/"
    // Action: Access the webpage "https://nhandan.vn/"
    // Action: Navigate to the URL "https://nhandan.vn/"
    // Action: Visit the link "https://nhandan.vn/"
    // Action: Go to the address "https://nhandan.vn/"
    // Action: Browse to the website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    // Action: Clicking on a random article in the main page, in this case the center article.
    // Action: Selecting a random article on the main page, specifically the center one.
    // Action: Choosing a random article from the main page, with emphasis on the center one.
    // Action: Clicking on a randomly selected article on the main page, particularly focusing on the center article.
    // Action: Selecting a random article from the main page, with the center article being the target.
    // Action: Engaging with a randomly chosen article on the main page, highlighting the center article for this instance.
    driver.findElement(By.xpath("//h2/a")).click();

    //Action: Clicking on the 3rd article on the "Tin đọc nhiều" section.
    //Action: Clicking on the 3rd article on the "Tin đọc nhiều" section.
    //Action: Choosing the third article within the "Tin đọc nhiều" section.
    //Action: Accessing the third article in the "Tin đọc nhiều" section by clicking.
    //Action: Clicking to view the third article listed under "Tin đọc nhiều".
    //Action: Navigating to the third article in the "Tin đọc nhiều" section with a click.
    driver.findElement(By.xpath("//div[2]/div[2]/article[3]/h3/a")).click();
    js.executeScript("window.scrollTo(0,59.20000076293945)");
    driver.close();
  }
}
