// Generated by Selenium IDE
package Article.anotherNewsFunctionality;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RecommendKeywordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public void waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
  @Test
  public void recommendKeyword() {

    // GENERAL DESCRIPTION: This test will check reading article with respect to the key word suggested by server.
    // WEB URL: "https://nhandan.vn/"

    // Action: Open the url "https://nhandan.vn/"
    // Action: Access the webpage "https://nhandan.vn/"
    // Action: Navigate to the URL "https://nhandan.vn/"
    // Action: Visit the link "https://nhandan.vn/"
    // Action: Go to the address "https://nhandan.vn/"
    // Action: Browse to the website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    // Action: Click on the center article in the main page.
    //Action: Clicking on the center article in the main page.
    //Action: Selecting the center article on the main page with a click.
    //Action: Accessing the center article on the main page by clicking.
    //Action: Engaging with the center article on the main page by clicking.
    //Action: Choosing the center article on the main page with a click.
    driver.findElement(By.xpath("//h2/a")).click();
    js.executeScript("window.scrollTo(0,444)");

    // Action: Click on the 2nd suggestion keyword.
    //Action: Click on the 2nd recommended keyword.
    //Action: Selecting the 2nd suggested keyword with a click.
    //Action: Accessing the 2nd recommended keyword by clicking.
    //Action: Engaging with the 2nd keyword suggestion by clicking.
    //Action: Choosing the 2nd keyword recommendation with a click.
    driver.findElement(By.xpath("//a[2]")).click();
    js.executeScript("window.scrollTo(0,91.19999694824219)");

    // Action: Click on the "Xem thêm" button.
    //Action: Click on the "Xem thêm" button.
    //Action: Selecting the "Xem thêm" button with a click.
    //Action: Accessing the "Xem thêm" option by clicking.
    //Action: Engaging the "Xem thêm" button with a click.
    //Action: Choosing the "Xem thêm" option by clicking on it.
    driver.findElement(By.cssSelector(".control__loadmore")).click();
    waitForWindow(5000);

    // Action: Click on the last article in this page.
    // Action: Clicking on the last article on this page.
    //Action: Selecting the final article on this page with a click.
    //Action: Accessing the last article on this page by clicking.
    //Action: Engaging with the last article on this page by clicking.
    //Action: Choosing the last article on this page with a click.
    driver.findElement(By.xpath("//article[60]/h3/a")).click();
    js.executeScript("window.scrollTo(0,326.3999938964844)");
    driver.close();
  }
}
