// Generated by Selenium IDE
package Article.checkAudioButton;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AudioCNN2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public void waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
  @Test
  public void audioCNN2() {
    // GENERAL DESCRIPTION: This test is checking audio function on the newspaper page
    // WEB URL: "https://edition.cnn.com/"

    // Action: Click on the url "https://edition.cnn.com/"
    //Action: Selecting the URL "https://edition.cnn.com/" with a click.
    //Action: Accessing the URL "https://edition.cnn.com/" by clicking.
    //Action: Engaging with the URL "https://edition.cnn.com/" by clicking.
    //Action: Choosing the URL "https://edition.cnn.com/" by clicking on it.
    driver.get("https://edition.cnn.com/");
    driver.manage().window().setSize(new Dimension(1536, 816));

    // Action: Click on the "Listen" button.
    //Action: Selecting the "Listen" button with a click.
    //Action: Accessing the "Listen" option by clicking.
    //Action: Engaging with the "Listen" button by clicking.
    //Action: Choosing the "Listen" option by clicking on it.
    driver.findElement(By.linkText("Listen")).click();
    waitForWindow(2000);

    // Action: Click the first series of the "Limited series" section.
    //Action: Selecting the initial series in the "Limited series" section with a click.
    //Action: Accessing the first series listed under the "Limited series" section by clicking.
    //Action: Engaging with the first series in the "Limited series" section by clicking.
    //Action: Choosing the first series of the "Limited series" section by clicking on it.
    driver.findElement(By.cssSelector("#special .item:nth-child(1) img")).click();
    waitForWindow(4000);

    // Action: click on the 6th episode in this series.
    //Action: Selecting the 6th episode in this series with a click.
    //Action: Accessing the 6th episode in this series by clicking.
    //Action: Engaging with the 6th episode in this series by clicking.
    //Action: Choosing the 6th episode in this series by clicking on it.
    driver.findElement(By.xpath("//audio-player-wc[6]")).click();
    waitForWindow(20000);

    // Action: Click on the pause button.
    //Action: Clicking on the pause button.
    //Action: Selecting the pause button with a click.
    //Action: Accessing the pause option by clicking.
    //Action: Engaging with the pause button by clicking.
    //Action: Choosing the pause option by clicking on it.
    driver.findElement(By.xpath("//button[2]")).click();
    driver.close();
  }
}
