// Generated by Selenium IDE
package Article.checkAudioButton;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AudioND2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void audioND2() {
    // General Description: This test is going to test the audio function of newspaper
    // Web URL: "https://nhandan.vn/"

    // Action: Open the url "https://nhandan.vn/"
    // Action: Access the webpage "https://nhandan.vn/"
    // Action: Navigate to the URL "https://nhandan.vn/"
    // Action: Visit the link "https://nhandan.vn/"
    // Action: Go to the address "https://nhandan.vn/"
    // Action: Browse to the website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(788, 816));
    js.executeScript("window.scrollTo(0,256)");

    // Action: Click on the center article in the main page.
    //Action: Clicking on the center article in the main page.
    //Action: Selecting the center article on the main page with a click.
    //Action: Accessing the center article on the main page by clicking.
    //Action: Engaging with the center article on the main page by clicking.
    //Action: Choosing the center article on the main page with a click.
    driver.findElement(By.xpath("//h2/a")).click();
    js.executeScript("window.scrollTo(0,351.20001220703125)");

    // Action: Click on the type of voice button and choose "Nam miền Nam".
    //Action: Click on the type of voice button and choose "Nam miền Nam".
    //Action: Selecting the voice type button and opting for "Nam miền Nam".
    //Action: Accessing the voice type button and selecting "Nam miền Nam".
    //Action: Engaging with the voice type button and choosing "Nam miền Nam".
    //Action: Clicking on the voice type button and selecting "Nam miền Nam".
    driver.findElement(By.cssSelector("#bm-player-dropdownbtn > span")).click();
    driver.findElement(By.cssSelector("li:nth-child(4) span")).click();

    // Action: click on the progress bar to tour the progress.
    //Action: Clicking on the progress bar to navigate through the progress.
    //Action: Selecting the progress bar to tour the progress.
    //Action: Accessing the progress bar to navigate through the progress.
    //Action: Engaging with the progress bar to tour the progress.
    //Action: Choosing the progress bar to navigate through the progress.
    driver.findElement(By.id("progress-bar")).click();
    driver.close();
  }
}
