// Generated by Selenium IDE
package Article.checkAudioButton;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AudioCNNTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void audioCNN() {
    // General Description: This test is checking audio function on the newspaper page.
    // Web URL: "https://edition.cnn.com/"

    // Action: Click on the url "https://edition.cnn.com/"
    //Action: Selecting the URL "https://edition.cnn.com/" with a click.
    //Action: Accessing the URL "https://edition.cnn.com/" by clicking.
    //Action: Engaging with the URL "https://edition.cnn.com/" by clicking.
    //Action: Choosing the URL "https://edition.cnn.com/" by clicking on it.
    driver.get("https://edition.cnn.com/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    // Action: Click on the "Listen" button.
    //Action: Selecting the "Listen" button with a click.
    //Action: Accessing the "Listen" option by clicking.
    //Action: Engaging with the "Listen" button by clicking.
    //Action: Choosing the "Listen" option by clicking on it.
    driver.findElement(By.linkText("Listen")).click();

    // Action: Clicking on the first series in the "Podcasts" section.
    //Action: Selecting the initial series in the "Podcasts" section with a click.
    //Action: Accessing the first series listed under the "Podcasts" section by clicking.
    //Action: Engaging with the first series in the "Podcasts" section by clicking.
    //Action: Choosing the first series of the "Podcasts" section by clicking on it.
    {
      WebElement element = driver.findElement(By.xpath("//a/div[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    //Action: Click on the first episode of this page.
    //Action: Selecting the initial episode of this page with a click.
    //Action: Accessing the first episode listed on this page by clicking.
    //Action: Engaging with the first episode on this page by clicking.
    //Action: Choosing the first episode of this page by clicking on it.
    driver.findElement(By.cssSelector(".item:nth-child(1) > .episode")).click();

    // Action : Clicking the pause button.
    // Action: Engaging the pause button
    //Action: Selecting the pause option
    //Action: Accessing the pause feature
    //Action: Choosing to pause
    //Action: Clicking on the button for pausing
    driver.findElement(By.id("control-play-pause")).click();

    // Action: Clicking the replay button.
    //Action: Engaging the replay button
    //Action: Selecting the replay option
    //Action: Accessing the replay feature
    //Action: Choosing to replay
    //Action: Clicking on the button for replay
    driver.findElement(By.id("control-replay")).click();

    // Action: Click the play button.
    // Action : Clicking the pause button.
    // Action: Engaging the pause button
    //Action: Selecting the pause option
    //Action: Accessing the pause feature
    //Action: Choosing to pause
    //Action: Clicking on the button for pausing
    driver.findElement(By.id("control-play-pause")).click();
  }
}
