// Generated by Selenium IDE
package search_page.searchingField;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingFieldBingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchingFieldBing() {
    // General Description: this code is checking the searching field of searching tool Bing with a random topic.
    // WEB URL : "https://www.bing.com/"

    //Action: Click on the URL "https://www.bing.com/" and enter "total solar eclipse" into the search field.
    //Action: Visit the URL "https://www.bing.com/" and type "total solar eclipse" into the search box.
    //Action: Open the URL "https://www.bing.com/" and input "total solar eclipse" into the search field.
    //Action: Navigate to the URL "https://www.bing.com/" and put "total solar eclipse" into the search field.
    //Action: Access the URL "https://www.bing.com/" and insert "total solar eclipse" into the search field.
    driver.get("https://www.bing.com/search?form=&q=total+solar+eclipse&form=QBLH&sp=-1&ghc=1&lq=0&pq=total+solar+eclipse&sc=10-19&qs=n&sk=&cvid=44B92D25F2B540238ACC149D538C725D&ghsh=0&ghacc=0&ghpl=");
    driver.manage().window().setSize(new Dimension(784, 804));

    //Action: Click on the first result appeared.
    //Action: Click on the first result appeared in the new page.
    //Action: Select the initial result that shows up on the fresh page.
    //Action: Choose the first outcome displayed on the newly opened page.
    //Action: Click on the initial search result visible on the recently loaded page.
    //Action: Opt for the first link that appears on the newly opened page.
    //Action: Click on the primary result presented on the fresh page.
    driver.findElement(By.linkText("Total Solar Eclipses Worldwide – Next 10 Years - timeanddate.com")).click();
    driver.close();
  }
}
