// Generated by Selenium IDE
package search_page.searchingField;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingFieldGoogle2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchingFieldGoogle2() {
    try {
      // 1. Clicl on the url: "https://www.google.com/"
      // 2. Sending "suicide" to the searching field
      // 2. Typing "suicide" in the searching field
      driver.get("https://www.google.com/search?q=suicide&sca_esv=3d5aec0ebbda9031&sxsrf=ACQVn0_nFGDxe4br5FjzJ7GSPdryi3XwTQ%3A1712616737156&source=hp&ei=IXUUZoPLB8DO1e8P8faRyAU&iflsig=ANes7DEAAAAAZhSDMV1wMTkA1oLvw0Uw43JUsIi4aHuw&udm=&ved=0ahUKEwjD34LC2rOFAxVAZ_UHHXF7BFkQ4dUDCBU&uact=5&oq=suicide&gs_lp=Egdnd3Mtd2l6IgdzdWljaWRlMgUQABiABDIFEAAYgAQyBRAAGIAEMgsQLhiABBixAxiDATIFEAAYgAQyBRAAGIAEMggQLhiABBixAzIFEAAYgAQyBRAAGIAEMgUQLhiABEjUElCuBFi-D3ABeACQAQCYAYkBoAH2BaoBAzIuNbgBA8gBAPgBAZgCCKACnAaoAgrCAgcQIxjqAhgnwgIKECMYgAQYigUYJ8ICChAuGIAEGIoFGEPCAgsQABiABBixAxiDAcICERAuGIAEGLEDGIMBGMcBGNEDwgIEEAAYA8ICDhAAGIAEGIoFGLEDGIMBwgIQEC4YgAQYigUYQxixAxiDAcICCBAAGIAEGLEDwgIHEAAYgAQYCpgDCJIHAzMuNaAHmFI&sclient=gws-wiz");
      driver.manage().window().setSize(new Dimension(784, 804));

      // 3. A annoucement is appeared on the top of the result page. Click "Call" button.
      // 3. Click on the phone label button.
      driver.findElement(By.cssSelector(".xPmOaf:nth-child(1) > .hhWEGd")).click();
      Thread.sleep(4000);
      driver.close();
    } catch(InterruptedException e) {

    }
  }
}
