// Generated by Selenium IDE
package search_page.searchingField;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingFieldBingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchingFieldBing() {
    // General description: searching field bing test
    // Web URL: https://www.bing.com/

    //1. Click on the url "ttps://www.bing.com/" and field "total solar eclipse" into the searching field.
    // 1. Open the bing search by link "ttps://www.bing.com/" and type "total solar eclipse" into the searching field.
    driver.get("https://www.bing.com/search?form=&q=total+solar+eclipse&form=QBLH&sp=-1&ghc=1&lq=0&pq=total+solar+eclipse&sc=10-19&qs=n&sk=&cvid=44B92D25F2B540238ACC149D538C725D&ghsh=0&ghacc=0&ghpl=");
    driver.manage().window().setSize(new Dimension(784, 804));

    // 2. Click on the first result you see.
    // 2. Click on the first link appeared on the result page.
    // Click on the first result appeared in the new page.
    // Select the initial result that shows up on the fresh page.
    //Choose the first outcome displayed on the newly opened page.
    //Click on the initial search result visible on the recently loaded page.
    //Opt for the first link that appears on the newly opened page.
    //Click on the primary result presented on the fresh page.
    driver.findElement(By.linkText("Total Solar Eclipses Worldwide – Next 10 Years - timeanddate.com")).click();
    driver.close();
  }
}
