// Generated by Selenium IDE
package search_page.searchingField;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingFieldGoogleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchingFieldGoogle() {
    // General description: searching field test
    // Web URL: https://www.google.com/

    try {

      // 1. Click on the url: "https://www.google.com/"
      // 2. Field "total solar eclipse" in the searching field
      driver.get("https://www.google.com/search?q=total+solar+eclipse&sca_esv=3d5aec0ebbda9031&sxsrf=ACQVn0_YF72oVt5N0CBlMht2RhdiR9WVZA%3A1712615214241&source=hp&ei=Lm8UZqPTDJy52roPrduimAY&iflsig=ANes7DEAAAAAZhR9PrZ5E6l97eIzEkD2Dxr_7wWuQzO-&udm=&ved=0ahUKEwijouvr1LOFAxWcnFYBHa2tCGMQ4dUDCBU&uact=5&oq=total+solar+eclipse&gs_lp=Egdnd3Mtd2l6IhN0b3RhbCBzb2xhciBlY2xpcHNlMgoQIxiABBiKBRgnMgQQABgDMgUQABiABDILEAAYgAQYsQMYgwEyBRAAGIAEMgUQABiABDIFEAAYgAQyCxAAGIAEGLEDGIMBMgYQABgWGB4yBhAAGBYYHkihUFAAWIZIcAZ4AJABAJgB4gGgAZQXqgEGOS4xNC4yuAEDyAEA-AEBmAIfoAKnGKgCCsICChAuGIAEGIoFGEPCAhEQLhiABBixAxiDARjHARjRA8ICDxAjGIAEGIoFGCcYRhj_AcICBBAjGCfCAgoQABiABBiKBRhDwgILEC4YgAQYsQMYgwHCAhAQABiABBiKBRhDGLEDGIMBwgIOEAAYgAQYigUYsQMYgwHCAggQABiABBixA8ICCBAuGIAEGLEDwgIREC4YgAQYxwEYrwEYmAUYmQXCAgsQLhiABBjHARivAcICBxAjGOoCGCfCAgwQIxiABBiKBRgTGCfCAg4QLhiDARjUAhixAxiABMICBRAuGIAEmAMFkgcHMTQuMTQuM6AHhOYB&sclient=gws-wiz");
      driver.manage().window().setSize(new Dimension(784, 804));
      Thread.sleep(3000);

      //3. Click on the first result appeared in the new page.
      // Select the initial result that shows up on the fresh page.
      //Choose the first outcome displayed on the newly opened page.
      //Click on the initial search result visible on the recently loaded page.
      //Opt for the first link that appears on the newly opened page.
      //Click on the primary result presented on the fresh page.
      driver.findElement(By.cssSelector(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)")).click();
      driver.close();
    } catch(InterruptedException e) {

    }
  }
}
