// Generated by Selenium IDE
package Article.checkFindingBasedOnType;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LDTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lD() {

    // General Description: This test is going to the finding function of the newspaper.
    // Web URL: "https://laodong.vn/"

    // Action: Open the url "https://laodong.vn/"
    //Action: Access the webpage "https://laodong.vn/"
    //Action: Navigate to the URL "https://laodong.vn/"
    //Action: Visit the link "https://laodong.vn/"
    //Action: Go to the address "https://laodong.vn/"
    //Action: Browse to the website "https://laodong.vn/"
    driver.get("https://laodong.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    // Action: Click on the "Bạn đọc" button.
    //Action: Select the "Bạn đọc" button with a click.
    //Action: Access the "Bạn đọc" button by clicking.
    //Action: Engage with the "Bạn đọc" button by clicking.
    //Action: Choose the "Bạn đọc" button by clicking on it.
    //Action: Click on the "Bạn đọc" option.
    driver.findElement(By.linkText("Bạn đọc")).click();

    // Action: Click on the "Ý kiến - Hồi âm" button.
    //Action: Select the "Ý kiến - Hồi âm" button with a click.
    //Action: Access the "Ý kiến - Hồi âm" button by clicking.
    //Action: Engage with the "Ý kiến - Hồi âm" button by clicking.
    //Action: Choose the "Ý kiến - Hồi âm" button by clicking on it.
    //Action: Click on the "Ý kiến - Hồi âm" option.
    driver.findElement(By.linkText("Ý kiến - Hồi âm")).click();
    js.executeScript("window.scrollTo(0,70)");
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 100).perform();
    }
    // Action: Click on the first article on the page.
    //Action: Selecting the initial article on the page with a click.
    //Action: Accessing the first article on the page by clicking.
    //Action: Engaging with the first article on the page by clicking.
    //Action: Choosing the first article on the page by clicking on it.
    //Action: Clicking on the first article displayed on the page.
    driver.findElement(By.xpath("//figure/img")).click();
    driver.close();
  }
}
