// Generated by Selenium IDE
package Article.checkFindingBasedOnType;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ND2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void nD2() {
    // General Description: This test is going to the finding function of the newspaper.
    // Web URL: "https://nhandan.vn/"

    // Action: Open the url "https://nhandan.vn/"
    // Action: Access the webpage "https://nhandan.vn/"
    // Action: Navigate to the URL "https://nhandan.vn/"
    // Action: Visit the link "https://nhandan.vn/"
    // Action: Go to the address "https://nhandan.vn/"
    // Action: Browse to the website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    // Action: Click on the button "Tin địa phương"
    //Action: Select the "Tin địa phương" button with a click.
    //Action: Access the "Tin địa phương" button by clicking.
    //Action: Engage with the "Tin địa phương" button by clicking.
    //Action: Choose the "Tin địa phương" button by clicking on it.
    //Action: Click on the "Tin địa phương" option.
    driver.findElement(By.cssSelector(".region-3 li:nth-child(2) > a")).click();

    // Action : Click on the button "Ninh Thuận"
    //Action: Select the "Ninh Thuận" button with a click.
    //Action: Access the "Ninh Thuận" button by clicking.
    //Action: Engage with the "Ninh Thuận" button by clicking.
    //Action: Choose the "Ninh Thuận" button by clicking on it.
    //Action: Click on the "Ninh Thuận" option.
    driver.findElement(By.linkText("Ninh Thuận")).click();
    driver.findElement(By.id("dlLocation")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".right-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    //Action:  Hover in the "Danh mục" listbox and click "Xã hội"
    //Action: Hover over the "Danh mục" listbox and click on "Xã hội".
    //Action: Position the cursor over the "Danh mục" listbox and select "Xã hội" by clicking.
    //Action: Move the cursor to the "Danh mục" listbox and click on "Xã hội".
    //Action: Navigate to the "Danh mục" listbox and choose "Xã hội" by clicking.
    //Action: Hover over the "Danh mục" listbox and choose "Xã hội" with a click.
    driver.findElement(By.linkText("Xã hội")).click();

    // Action: Click the first article apppeared.
    //Action: Select the initial article displayed.
    //Action: Access the first article shown.
    //Action: Choose the first appearing article.
    //Action: Click on the first article visible.
    //Action: Engage with the first article presented.
    driver.findElement(By.xpath("//h2/a")).click();
    js.executeScript("window.scrollTo(0,328)");
    driver.close();
  }
}
