// Generated by Selenium IDE
package Article.checkFindingBasedOnType;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TNMTTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tNMT() {
    // GENERAL DESCRIPTION: this test well checking reading article by topic.
    // WEB URL: "https://baotainguyenmoitruong.vn/"

    // Action: Open the url "https://baotainguyenmoitruong.vn/"
    //Action: Access the webpage "https://baotainguyenmoitruong.vn/"
    //Action: Navigate to the URL "https://baotainguyenmoitruong.vn/"
    //Action: Visit the link "https://baotainguyenmoitruong.vn/"
    //Action: Go to the address "https://baotainguyenmoitruong.vn/"
    //Action: Browse to the website "https://baotainguyenmoitruong.vn/"
    driver.get("https://baotainguyenmoitruong.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    js.executeScript("window.scrollTo(0,42.400001525878906)");

    //Action: Click on the menu expanding button
    //Action: Select the menu expanding button with a click.
    //Action: Access the menu expanding button by clicking.
    //Action: Engage with the menu expanding button by clicking.
    //Action: Choose the menu expanding button by clicking on it.
    //Action: Click on the menu expanding option.
    driver.findElement(By.cssSelector(".c-menu-expand")).click();

    // Action: Click on the "Phát triển xanh" section.
    driver.findElement(By.cssSelector(".c-mega-menu__child:nth-child(10) > a")).click();

    // Action: Click on the "Chuyển đổi xanh" button.
    //Action: Select the "Phát triển xanh" section with a click.
    //Action: Access the "Phát triển xanh" section by clicking.
    //Action: Engage with the "Phát triển xanh" section by clicking.
    //Action: Choose the "Phát triển xanh" section by clicking on it.
    //Action: Click on the "Phát triển xanh" section option.
    driver.findElement(By.linkText("Chuyển đổi Xanh")).click();

    // Action: Click on the first article apppeared.
    //Action: Select the first appearing article with a click.
    //Action: Access the first article that appears by clicking.
    //Action: Engage with the first appearing article by clicking.
    //Action: Choose the first article that appears by clicking on it.
    //Action: Click on the first appearing article option.
    driver.findElement(By.xpath("//div/h2/a")).click();

    // Action: Click on the comment field.
    //Action: Select the comment field by clicking.
    //Action: Access the comment field by clicking.
    //Action: Engage with the comment field by clicking.
    //Action: Choose the comment field by clicking on it.
    //Action: Click on the comment field option.
    driver.findElement(By.cssSelector(".txt-content")).click();

    // Action: Field "Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển." onto the comment field.
    //Action: Input "Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển." into the comment field.
    //Action: Type "Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển." into the comment field.
    //Action: Enter "Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển." into the comment field.
    //Action: Place "Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển." onto the comment field.
    //Action: Input the text "Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển." into the comment field.
    driver.findElement(By.cssSelector(".txt-content")).sendKeys("Nội dung hay và có ý nghĩa, mong rằng dự án sẽ phát triển.");

    // Action: Click on the " Gửi bình luận" button.
    //Action: Select the "Gửi bình luận" button with a click.
    //Action: Access the "Gửi bình luận" button by clicking.
    //Action: Engage with the "Gửi bình luận" button by clicking.
    //Action: Choose the "Gửi bình luận" button by clicking on it.
    //Action: Click on the "Gửi bình luận" button option.
    driver.findElement(By.cssSelector(".btn")).click();

    //Action: Field "Black" into "Họ và tên" field.
    //Action: Enter "Black" into the "Họ và tên" field.
    //Action: Input "Black" into the "Họ và tên" field.
    //Action: Type "Black" into the "Họ và tên" field.
    //Action: Place "Black" into the "Họ và tên" field.
    //Action: Input the text "Black" into the "Họ và tên" field.
    driver.findElement(By.cssSelector(".box:nth-child(1)")).click();
    driver.findElement(By.id("txtName")).click();
    driver.findElement(By.id("txtName")).sendKeys("Black");

    // Action: Field "cd@gmail.com" into the "Email" field.
    //Action: Enter "cd@gmail.com" into the "Email" field.
    //Action: Input "cd@gmail.com" into the "Email" field.
    //Action: Type "cd@gmail.com" into the "Email" field.
    //Action: Place "cd@gmail.com" into the "Email" field.
    //Action: Input the text "cd@gmail.com" into the "Email" field.
    driver.findElement(By.id("txtEmail")).click();
    driver.findElement(By.id("txtEmail")).sendKeys("cd@gmail.com");

    // Action: Click "Gửi" button.
    //Action: Select the "Gửi" button with a click.
    //Action: Access the "Gửi" button by clicking.
    //Action: Engage with the "Gửi" button by clicking.
    //Action: Choose the "Gửi" button by clicking on it.
    //Action: Click on the "Gửi" button option.
    driver.findElement(By.linkText("Gửi")).click();
    driver.close();
  }
}
