// Generated by Selenium IDE
package Article.anotherNewsFunctionality.changeLanguage;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangeLanguageEnglishTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void changeLanguageEnglish() {
    // General Description: This test is about checking whether newspaper works well in another language.
    // Web url: https://nhandan.vn/

    // Action: Open the url "https://nhandan.vn/"
    // Action: Access the webpage "https://nhandan.vn/"
    // Action: Navigate to the URL "https://nhandan.vn/"
    // Action: Visit the link "https://nhandan.vn/"
    // Action: Go to the address "https://nhandan.vn/"
    // Action: Browse to the website "https://nhandan.vn/"
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    vars.put("window_handles", driver.getWindowHandles());

    //Action: Click on the "English" button
    //Action: Clicking on the "English" button.
    //Action: Selecting the "English" button with a click.
    //Action: Accessing the "English" option by clicking.
    //Action: Engaging the "English" button with a click.
    //Action: Choosing the "English" option by clicking on the button.
    driver.findElement(By.linkText("English")).click();
    vars.put("win6643", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win6643").toString());


    //Action: Click on the center article in the English newspaper page's version.
    //Action: Clicking on the center article in the English newspaper page's version.
    //Action: Selecting the center article in the English newspaper page's version with a click.
    //Action: Accessing the center article in the English newspaper page's version by clicking.
    //Action: Engaging the center article in the English newspaper page's version with a click.
    //Action: Choosing the center article in the English newspaper page's version by clicking on it.
    driver.findElement(By.xpath("//h2/a")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
}
