package Article.openArticleLink;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class openArticleVNnet {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void openArticleVNnet() {
        driver.get("https://vietnamnet.vn/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        {
            WebElement element = driver.findElement(By.cssSelector(".header__logo img"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.linkText("Thời sự"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".mainNav__list-item:nth-child(5)")).click();
        driver.findElement(By.linkText("Thể thao")).click();
        js.executeScript("window.scrollTo(0,68)");
        js.executeScript("window.scrollTo(0,1220)");
        js.executeScript("window.scrollTo(0,1276)");
        js.executeScript("window.scrollTo(0,1751.199951171875)");
        js.executeScript("window.scrollTo(0,2044.800048828125)");
        js.executeScript("window.scrollTo(0,2268)");
        driver.findElement(By.cssSelector(".boxCate:nth-child(6) .boxCateItem:nth-child(1) > .boxCateItem__main a")).click();
        js.executeScript("window.scrollTo(0,88)");
        driver.close();
    }
}
