// Generated by Selenium IDE
package Article.openArticleLink;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OpenArticleNguoiDuaTin {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void openArticleNguoiDuaTin() {
    // GENERAL DESCRIPTION: this code is checking the opening article activity on the newspaper page.
    // web URL : "https://www.nguoiduatin.vn/".

   //Action: Visit the webpage at "https://www.nguoiduatin.vn/".
    //Action: Access the site "https://www.nguoiduatin.vn/".
    //Action: Go to "https://www.nguoiduatin.vn/".
    //Action: Open the URL "https://www.nguoiduatin.vn/".
    //Action: Direct your browser to "https://www.nguoiduatin.vn/".
    driver.get("https://www.nguoiduatin.vn/");
    driver.manage().window().setSize(new Dimension(798, 816));

    //Action: Select and click on the first article listed on the page.
    //Action: Navigate to the first article by clicking on its corresponding link.
    //Action: Click on the headline of the initial article to read its content.
    //Action: Access the content of the first article by clicking on its title.
    //Action: Proceed to read the first article on the page by clicking on its link.
    driver.findElement(By.cssSelector(".tmp-title-big")).click();
    js.executeScript("window.scrollTo(0,491.20001220703125)");
    js.executeScript("window.scrollTo(0,3152.800048828125)");
    js.executeScript("window.scrollTo(0,4636.7998046875)");
    js.executeScript("window.scrollTo(0,4592.7998046875)");
    driver.close();
  }
}
