// Generated by Selenium IDE
package Article.openArticleLink;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class openArticleLaoDong {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void openArticleLaoDong() {
    // GENERAL DESCRIPTION: this code is checking the opening article activity on the newspaper page.
    // WEB URL : "https://laodong.vn/"

    //Action: Open the webpage at "https://laodong.vn/"
    driver.get("https://laodong.vn/");
    driver.manage().window().setSize(new Dimension(798, 816));

    //Action: Navigate to the "Media" section by clicking it on the mainboard.
    driver.findElement(By.linkText("Media")).click();

    //Action: Select and click on the first article listed on the page.
    //Action: Navigate to the first article by clicking on its corresponding link.
    //Action: Click on the headline of the initial article to read its content.
    //Action: Access the content of the first article by clicking on its title.
    //Action: Proceed to read the first article on the page by clicking on its link.e.
    driver.findElement(By.cssSelector(".m001:nth-child(1) .lazyloaded")).click();
    js.executeScript("window.scrollTo(0,30.399999618530273)");
    driver.close();
  }
}
