// Generated by Selenium IDE
package Article.openArticleLink;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class openArticleNhanDan {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void openArticleNhanDan() {
    // GENERAL DESCRIPTION: this code is checking the opening article activity on the newspaper page.
    // web URL : "https://nhandan.vn/"

    //Action: Visit the website at the following URL: "https://nhandan.vn/".
    //Action: Access the link: 'https://nhandan.vn/".
    //Action: Navigate to 'https://nhandan.vn/' by clicking on the URL.
    //Action: Follow the hyperlink provided: 'https://nhandan.vn/'.
    //Action: Direct your browser to 'https://nhandan.vn/' by selecting the link.
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(793, 816));

    //Action: Click on the most breaking news on the page.
    //Action: Select the latest breaking news article on the page.
    //Action: Click on the headline of the most recent breaking news.
    //Action: Navigate to the top breaking news story by clicking it.
    //Action: Choose the breaking news item that stands out the most and click on it.
    driver.findElement(By.xpath("//h2/a")).click();
    driver.close();
  }
}
