

// Generated by Selenium IDE
package Article.openArticleLink;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class openArticalTNT {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void openArticalTNT() {

        // General Description: this code is checking the opening article activity on the newspaper page.
        // web URL :  "https://www.nytimes.com/"

       //Action: Access The New York Times website at "https://www.nytimes.com/".
        //Action: Visit The New York Times homepage.
        //Action: Navigate to The New York Times webpage using the provided URL.
        //Action: Direct the browser to The New York Times website.
        //Action: Open The New York Times site to read articles.
        driver.get("https://www.nytimes.com/");
        driver.manage().window().setSize(new Dimension(1536, 816));
        {
            WebElement element = driver.findElement(By.cssSelector(".css-17j7fe1 > .css-1fbfcor:nth-child(2) > .css-chopks"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }

        //Action: Select and click on the hyperlink labeled "World" on the webpage.
        //Action: Navigate to the "World" section by clicking on the corresponding link.
        //Action: Access the "World" category by clicking on the associated hyperlink.
        //Action: Follow the link labeled "World" to explore global news articles.
        //Action: Click on the link with the text "World" to view international news.
        {
            WebElement element = driver.findElement(By.linkText("World"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.linkText("World")).click();

       //Action: Select and click on the first article listed on the page.
        //Action: Navigate to the first article by clicking on its corresponding link.
        //Action: Click on the headline of the initial article to read its content.
        //Action: Access the content of the first article by clicking on its title.
        //Action: Proceed to read the first article on the page by clicking on its link.
        {
            WebElement element = driver.findElement(By.cssSelector(".css-wcisuz:nth-child(6) > .css-1xphjhj"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".css-wcisuz:nth-child(6) > .css-1xphjhj")).click();
        driver.findElement(By.xpath("//article/a")).click();
        driver.close();
    }
}
