// Generated by Selenium IDE
package Article.checkSearchingFilter;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingTest3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchingTest3() {
    try {
      driver.get("https://nhandan.vn/");
      driver.manage().window().maximize();
      driver.findElement(By.cssSelector(".fa-search:nth-child(1)")).click();
      Thread.sleep(5000);
      driver.findElement(By.cssSelector(".txtsearch")).click();
      Thread.sleep(2000);
      driver.findElement(By.cssSelector(".txtsearch")).sendKeys("Nam Định");
      driver.findElement(By.cssSelector(".txtsearch")).sendKeys(Keys.ENTER);
      {
        WebElement element = driver.findElement(By.linkText("中文"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      driver.findElement(By.id("dlTime")).click();
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("dlTime"));
        dropdown.findElement(By.xpath("//option[. = 'Tháng trước']")).click();
      }
      driver.findElement(By.id("dlZone")).click();
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("dlZone"));
        dropdown.findElement(By.xpath("//option[. = 'Thể thao']")).click();
      }

      driver.findElement(By.id("dlMode")).click();
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("dlMode"));
        dropdown.findElement(By.xpath("//option[. = 'Theo tiêu đề']")).click();
      }
      driver.findElement(By.linkText("[Ảnh] Nam Định vững ngôi đầu V-League")).click();
      driver.close();
    } catch (InterruptedException e) {

    }
  }
}
