// Generated by Selenium IDE
package Article.checkSearchingFilter;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchND3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchND3() {

    // General Description: this code is checking the filter article functionality of newspaper page.
    // web URL "https://nhandan.vn/"

    ///Action: Click on the URL: "https://nhandan.vn/"
    //Action: Visit the website at the following URL: "https://nhandan.vn/".
    //Action: Access the link: 'https://nhandan.vn/".
    //Action: Navigate to 'https://nhandan.vn/' by clicking on the URL.
    //Action: Follow the hyperlink provided: 'https://nhandan.vn/'.
    //Action: Direct your browser to 'https://nhandan.vn/' by selecting the link.
    driver.get("https://nhandan.vn/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    {
      WebElement element = driver.findElement(By.cssSelector(".search-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // Action: Click on the searching field.
    //Action: Select the searching field by clicking.
    //Action: Access the searching field by clicking.
    //Action: Engage with the searching field by clicking.
    //Action: Choose the searching field by clicking on it.
    //Action: Click on the searching field option.
    driver.findElement(By.cssSelector(".search-button")).click();
    driver.findElement(By.cssSelector(".txtsearch")).click();
    driver.findElement(By.cssSelector(".txtsearch")).sendKeys(Keys.ENTER);

    // Action: Sending "." to the searching field.
    driver.findElement(By.cssSelector(".txtsearch")).sendKeys(".");
    driver.findElement(By.cssSelector(".txtsearch")).sendKeys(Keys.ENTER);

    // Action: Select "hôm qua" for the "Thời gian" listbox
    driver.findElement(By.id("dlTime")).click();
    {
      WebElement dropdown = driver.findElement(By.id("dlTime"));
      dropdown.findElement(By.xpath("//option[. = 'Hôm qua']")).click();
    }
    driver.close();
  }
}
