// Generated by Selenium IDE
package Article.checkSearchingFilter;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchingTest3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchingTest3() {

    // GENERAL DESCRIPTION: this code is checking the filter article functionality of newspaper page.
    // web URL "https://nhandan.vn/"
    try {

      //Action: Click on the URL: "https://nhandan.vn/"
      //Action: Visit the website at the following URL: "https://nhandan.vn/".
      //Action: Access the link: 'https://nhandan.vn/".
      //Action: Navigate to 'https://nhandan.vn/' by clicking on the URL.
      //Action: Follow the hyperlink provided: 'https://nhandan.vn/'.
      //Action: Direct your browser to 'https://nhandan.vn/' by selecting the link.
      driver.get("https://nhandan.vn/");
      driver.manage().window().maximize();

      //Action: Click on the searching button.
      //Action: Click on the button that have the magnifying glass label.
      driver.findElement(By.cssSelector(".fa-search:nth-child(1)")).click();
      Thread.sleep(5000);

      //Action: Field "Nam Dinh" into the searching field.
      driver.findElement(By.cssSelector(".txtsearch")).click();
      Thread.sleep(2000);
      driver.findElement(By.cssSelector(".txtsearch")).sendKeys("Nam Định");
      driver.findElement(By.cssSelector(".txtsearch")).sendKeys(Keys.ENTER);
      {
        WebElement element = driver.findElement(By.linkText("中文"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      //Action: In the filter article page, click on the "Thời gian" listbox
      // and set this field "Tháng trước".
      driver.findElement(By.id("dlTime")).click();
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("dlTime"));
        dropdown.findElement(By.xpath("//option[. = 'Tháng trước']")).click();
      }

      //Action: Next, click on the "Chuyên mục" listbox
      // and set this field "Thể thao".
      driver.findElement(By.id("dlZone")).click();
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("dlZone"));
        dropdown.findElement(By.xpath("//option[. = 'Thể thao']")).click();
      }

      //Action: click on the "Tìm theo" listbox and set this field "Theo tiêu đề".
      driver.findElement(By.id("dlMode")).click();
      Thread.sleep(3000);
      {
        WebElement dropdown = driver.findElement(By.id("dlMode"));
        dropdown.findElement(By.xpath("//option[. = 'Theo tiêu đề']")).click();
      }

      //Action : Click on the first article that appeared after filtering.
      driver.findElement(By.xpath("//h3/a")).click();
      driver.close();
    } catch (InterruptedException e) {

    }
  }
}
