// Generated by Selenium IDE
package Article.checkSearchingFilter;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SearchingTest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchingTest1() {

    // General Description: this code is checking the filter article functionality of newspaper page.
    // web URL "https://vietnamnet.vn/"

    try {
      //Action: Direct the WebDriver to the Vietnamnet website at "https://vietnamnet.vn/".
      //Action: Access the Vietnamnet homepage using the provided URL.
      //Action: Open the Vietnamnet website in the browser window.
      //Action: Visit the Vietnamnet webpage to read the latest news and articles.
      //Action: Load the Vietnamnet site to explore updates on various topics.
      driver.get("https://vietnam.vnanet.vn/vietnamese/");
      driver.manage().window().maximize();

    //Action: Select the searching icon with a click.
      //Action: Access the searching icon by clicking.
      //Action: Engage with the searching icon by clicking.
      //Action: Choose the searching icon by clicking on it.
      //Action: Click on the searching icon option.
      driver.findElement(By.cssSelector(".icon-search")).click();
      Thread.sleep(1000);

      // Action:  Field "Nam Định" into the searching field.
      //Action: Enter "Nam Định" into the searching field.
      //Action: Input "Nam Định" into the searching field.
      //Action: Type "Nam Định" into the searching field.
      //Action: Place "Nam Định" into the searching field.
      //Action: Input the text "Nam Định" into the searching field.
      driver.findElement(By.id("txtkeyword")).click();
      driver.findElement(By.id("txtkeyword")).sendKeys("Nam Định");

      // Action: In the filtering page, click on the "Từ ngày" listbox.
      //Action: Select the "Từ ngày" listbox in the filtering page with a click.
      //Action: Access the "Từ ngày" listbox in the filtering page by clicking.
      //Action: Engage with the "Từ ngày" listbox in the filtering page by clicking.
      //Action: Choose the "Từ ngày" listbox in the filtering page by clicking on it.
      //Action: Click on the "Từ ngày" listbox option in the filtering page.
      driver.findElement(By.cssSelector("#btnsearch > svg")).click();
      driver.findElement(By.id("ContentPlaceHolder1_uc_zone_search_advance_fromdate")).click();
      Thread.sleep(1000);

      //Action: Select the date of starting time for filtering is 1.
      //Action: Choose 1 as the starting date for filtering.
      //Action: Select 1 as the starting date for filtering.
      //Action: Set the starting time for filtering to 1.
      //Action: Specify 1 as the starting date for filtering.
      //Action: Indicate that the starting time for filtering is 1.
      driver.findElement(By.linkText("1")).click();

      //Action: Select the "Đến ngày" listbox by clicking.
      //Action: Access the "Đến ngày" listbox by clicking.
      //Action: Engage with the "Đến ngày" listbox by clicking.
      //Action: Choose the "Đến ngày" listbox by clicking on it.
      //Action: Click on the "Đến ngày" listbox option.
      driver.findElement(By.id("ContentPlaceHolder1_uc_zone_search_advance_todate")).click();
      Thread.sleep(1000);

      //Action: Select the date of ending time for filtering is 6.
      //Action: Choose 6 as the ending date for filtering.
      //Action: Select 6 as the ending date for filtering.
      //Action: Set the ending time for filtering to 6.
      //Action: Specify 6 as the ending date for filtering.
      //Action: Indicate that the ending time for filtering is 6.
      driver.findElement(By.linkText("6")).click();

      //Action: Click on the "Chuyên mục" listbox and then select "Tin Tức".
      //Action: Click on the "Chuyên mục" listbox and then choose "Tin Tức".
      //Action: Select "Tin Tức" after clicking on the "Chuyên mục" listbox.
      //Action: Access the "Chuyên mục" listbox and then click "Tin Tức".
      //Action: Engage with the "Chuyên mục" listbox and then select "Tin Tức".
      //Action: Choose "Tin Tức" from the "Chuyên mục" listbox after clicking.
      driver.findElement(By.id("ddlChuyenMuc_select")).click();
      Thread.sleep(1000);
      {
        WebElement dropdown = driver.findElement(By.id("ddlChuyenMuc_select"));
        dropdown.findElement(By.xpath("//option[. = 'Tin tức']")).click();
      }

      //Action: Click on the first article appeared.
      //Action: Select the first appearing article with a click.
      //Action: Access the first article that appears by clicking.
      //Action: Engage with the first appearing article by clicking.
      //Action: Choose the first article that appears by clicking on it.
      //Action: Click on the first appearing article option.
      driver.findElement(By.cssSelector(".btn-search-nc")).click();
      Thread.sleep(1000);
      driver.close();
    } catch (InterruptedException e) {
    }
  }
}
