// Generated by Selenium IDE
package Article.checkSearchingFilter;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SearchingTest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchingTest1() {
    try {
      //1. Direct the WebDriver to the Vietnamnet website at "https://vietnamnet.vn/".
      //Access the Vietnamnet homepage using the provided URL.
      //Open the Vietnamnet website in the browser window.
      //Visit the Vietnamnet webpage to read the latest news and articles.
      //Load the Vietnamnet site to explore updates on various topics.
      driver.get("https://vietnam.vnanet.vn/vietnamese/");
      driver.manage().window().maximize();

      //2. Click on the searching icon.
      driver.findElement(By.cssSelector(".icon-search")).click();
      Thread.sleep(1000);

      // 3. Field "Nam Định" into the searching field.
      driver.findElement(By.id("txtkeyword")).click();
      driver.findElement(By.id("txtkeyword")).sendKeys("Nam Định");

      // 4. In the filtering page, click on the "Từ ngày" listbox.
      driver.findElement(By.cssSelector("#btnsearch > svg")).click();
      driver.findElement(By.id("ContentPlaceHolder1_uc_zone_search_advance_fromdate")).click();
      Thread.sleep(1000);

      //5. Select the date of starting time for filtering is 1.
      driver.findElement(By.linkText("1")).click();

      // 6. click on the "Đến ngày" listbox.
      driver.findElement(By.id("ContentPlaceHolder1_uc_zone_search_advance_todate")).click();
      Thread.sleep(1000);

      //7.Select the date of ending time for filtering is 6.
      driver.findElement(By.linkText("6")).click();

      //8. Click on the "Chuyên mục" listbox and then select "Tin Tức".
      driver.findElement(By.id("ddlChuyenMuc_select")).click();
      Thread.sleep(1000);
      {
        WebElement dropdown = driver.findElement(By.id("ddlChuyenMuc_select"));
        dropdown.findElement(By.xpath("//option[. = 'Tin tức']")).click();
      }

      // 9. Click on the first article appeared.
      driver.findElement(By.cssSelector(".btn-search-nc")).click();
      Thread.sleep(1000);
      driver.close();
    } catch (InterruptedException e) {
    }
  }
}
