package music_player_page;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import java.time.Duration;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import org.openqa.selenium.chrome.ChromeOptions;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Login01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
//    System.setProperty("webdriver.chrome.driver", "/C://Users//HP//Desktop//IntelliJ//OOP//TestScriptGen//libs//Selenium//selenium-chrome-driver-4.18.1.jar/");
//    ChromeOptions options = new ChromeOptions();
//
//    // Tắt thông báo cảnh báo và chấp nhận tất cả cookies
//    options.addArguments("--disable-notifications");
//    options.addArguments("--disable-extensions");
//    options.addArguments("--disable-popup-blocking");
//    options.addArguments("--disable-save-password-bubble");
//    options.addArguments("--disable-features=CookieFeatures::SameSiteByDefaultCookies,CookieFeatures::SameSiteDefaultChecks");
//    options.addArguments("--accept-all-cookies");


    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login01() {
    driver.get("https://soundcloud.com/");
    driver.manage().window().setSize(new Dimension(800, 816));

    By cookies_accept = By.xpath("//*[@title='Accept Cookies']");
    By cookies_gotIt = By.xpath("//a[text()='Got it!']");

    //create web driver wait
    Duration waitDuration = Duration.ofSeconds(10);
    WebDriverWait wait = new WebDriverWait(driver, waitDuration);

    {
      WebElement loginButton = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".frontHero__loginButton")));
      WebElement element = driver.findElement(By.cssSelector(".frontHero__loginButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
      driver.findElement(By.cssSelector(".frontHero__loginButton")).click();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().frame(3);
    driver.findElement(By.id("sign_in_up_email")).click();
    driver.findElement(By.id("sign_in_up_email")).sendKeys("dominhsang2003.haihaua@gmail.com");
    driver.findElement(By.id("sign_in_up_submit")).click();
    driver.findElement(By.id("enter_password_field")).sendKeys("sang123456");
    driver.findElement(By.id("enter_password_submit")).click();
  }
}
