package music_player_page;
//test bai hat -> nhac trinh -> one song -> stop, play button -> next button
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Zingmusic01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void zingmusic01() {
    driver.get("https://www.nhaccuatui.com/");
    driver.manage().window().setSize(new Dimension(1552, 832));

    Duration waitDuration = Duration.ofSeconds(10);

    driver.findElement(By.linkText("Bài Hát")).click();
    driver.findElement(By.linkText("Nhạc Trịnh")).click();
    //wait for web loading
    WebDriverWait wait = new WebDriverWait(driver, waitDuration);

    driver.findElement(By.cssSelector("li:nth-child(5) > .box-content-music-list img")).click();
    driver.findElement(By.id("playButtonflashPlayer")).click();
    driver.findElement(By.id("playButtonflashPlayer")).click();
    driver.findElement(By.id("nextAutoPlayButtonflashPlayer")).click();
    driver.findElement(By.id("playButtonflashPlayer")).click();

  }
}
